import type { Command } from "commander";
import { buildSyncPlan, type SyncPlan, type SyncPlanBook, type SyncPlanRemovedBook } from "../lib/sync";
import { loadCommandContext, printCommandError } from "./context";

type PlanOptions = {
  book?: string;
  json?: boolean;
  vault?: string;
};

function printBook(item: SyncPlanBook | SyncPlanRemovedBook): void {
  const outputPath = item.bookFileRelativePath ? ` -> ${item.bookFileRelativePath}` : "";
  console.log(`  - [${item.format}] ${item.title} (${item.reason})${outputPath}`);
}

function printPlan(plan: SyncPlan): void {
  console.log("Sync plan");
  console.log("");
  console.log(`Output: ${plan.outputDir}`);
  console.log("");

  console.log("Changed:");
  if (plan.changed.length === 0) {
    console.log("  none");
  } else {
    for (const item of plan.changed) {
      printBook(item);
    }
  }
  console.log("");

  console.log("Removed:");
  if (plan.removed.length === 0) {
    console.log("  none");
  } else {
    for (const item of plan.removed) {
      printBook(item);
    }
  }
  console.log("");

  console.log("Unchanged:");
  console.log(`  ${plan.unchanged.length} books`);
  console.log("");

  console.log(
    `Summary: total=${plan.stats.totalBooks}, changed=${plan.stats.changedBooks}, unchanged=${plan.stats.unchangedBooks}, removed=${plan.stats.removedBooks}`,
  );
}

export function registerPlanCommand(program: Command): void {
  program
    .command("plan")
    .description("Preview which books need synchronization")
    .addHelpCommand(false)
    .showHelpAfterError("(run `absync plan --help` for usage)")
    .option("--vault <selector>", "target vault id, vault name, or path")
    .option("--book <keyword>", "plan only books matching keyword, title, author, or asset id")
    .option("--json", "print machine-readable JSON output")
    .addHelpText(
      "after",
      `
What this does:
  Reads the target vault plugin settings, output state, and Apple Books databases, then reports what
  absync sync would update or remove. It does not write files.

Prerequisites:
  Apple Books Notes Sync must be installed and enabled in the target vault.

Output groups:
  Changed
    Books that would be regenerated by absync sync.

  Removed
    Previously synced books that no longer exist in Apple Books.
    Removals are only planned during a full plan, not when --book is used.

  Unchanged
    Books whose current output already matches the current Apple Books data.

Change reasons:
  new
    No previous sync state exists for this book.

  content-changed
    Apple Books annotations or the source PDF file stamp changed.

  format-changed
    The book format changed between EPUB and PDF.

  output-path-changed
    The generated Markdown path changed, usually because the title/path changed.

  legacy-output
    Existing output was produced by an older output format and should be refreshed.

  missing-output
    Sync state exists, but the expected Markdown file is missing.

  pdf-assets-missing
    PDF image assets are missing while prior sync state exists.

  cover-assets-missing
    Cover image asset is missing while prior sync state expects one.

  removed
    Prior sync state exists, but the book is no longer in Apple Books.

Examples:
  absync plan
  absync plan --vault "MyVault"
  absync plan --book "Newton"
  absync plan --json
`,
    )
    .action((options: PlanOptions) => {
      void (async () => {
        const { config, paths } = await loadCommandContext(options);
        const planOptions: { bookFilter?: string } = {};
        if (options.book) {
          planOptions.bookFilter = options.book;
        }
        const plan = await buildSyncPlan(config, paths, planOptions);

        if (options.json) {
          console.log(
            JSON.stringify(
              {
                outputDir: plan.outputDir,
                summary: plan.stats,
                changed: plan.changed,
                unchanged: plan.unchanged,
                removed: plan.removed,
              },
              null,
              2,
            ),
          );
          return;
        }

        printPlan(plan);
      })().catch((error: unknown) => {
        printCommandError(error, "plan failed");
      });
    });
}
